# -*- coding: utf-8 -*-
"""step1.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1H1og7c-dqnkWeXvxjdBUiFg0ZuAOjC5c
"""

# STEP 1: Install ClearML in Colab
!pip install clearml

!clearml-init

import os

# Set ClearML credentials directly in Colab (replace only if different)
os.environ["CLEARML_API_ACCESS_KEY"] = "91A7AJN241YMJXE40LLNSX198E0JK4"
os.environ["CLEARML_API_SECRET_KEY"] = "m4S8vxmP0P5m3EZAZ_0IO6t1_5L2rz15bCyxYc5VS0kcQxlb4wUH2NLDzHT9kEus_z4"
os.environ["CLEARML_API_HOST"] = "https://api.clear.ml"
os.environ["CLEARML_WEB_HOST"] = "https://app.clear.ml"
os.environ["CLEARML_FILES_HOST"] = "https://files.clear.ml"

from clearml import Task

Task.init(
    project_name="plantdataset",
    task_name="Colab Connected Manually"
)

# Close the existing task
Task.current_task().close()

from clearml import Task, Dataset

# 🔁 Start a new ClearML Task
task = Task.init(
    project_name="plantdataset",
    task_name="Upload New Augmented Plant Disease Dataset"
)

# 📂 Your dataset path
dataset_path = "/content/drive/MyDrive/AIStudio/Project/Plant_Disease_Dataset/New Plant Diseases Dataset(Augmented)"

# ✅ Create dataset
dataset = Dataset.create(
    dataset_name="New Augmented Plant Disease Dataset",
    dataset_project="plantdataset"
)

# 📝 Optional description
dataset.set_description("Augmented dataset with multiple plant disease classes")

# 🚀 Upload
dataset.add_files(path=dataset_path)
dataset.upload()
dataset.finalize()